config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'blog', to: 'pages#blog'
  get 'professional', to: 'pages#professional'
  get 'terms' , to: 'pages#terms'
  get 'privacy' , to: 'pages#privacy'
  get 'cookies', to: 'pages#cookies'
  get 'contact', to: 'pages#contact'
  get 'stress', to: 'pages#stress'
  get 'careers', to: 'pages#careers'
  get "three-things-we-should-have-been-taught-at-school" , to: 'pages#three-things-we-should-have-been-taught-at-school'
  get "accounting-software-for-small-businesses" , to: 'pages#accounting-software-for-small-businesses'
  get "financial-security" , to: 'pages#financial-security'
  get "making-money-while-sleeping" , to: 'pages#making-money-while-sleeping'
  get "staying-safe-online" , to: 'pages#staying-safe-online'
  get "five-money-supersitions" , to: 'pages#five-money-supersitions'
  get "dream-house-dream-price" , to: 'pages#dream-house-dream-price'
  get "money-muling" , to: 'pages#money-muling'
  get "small-business-grants" , to: 'pages#small-business-grants'
  get "intellectual-property-law" , to: 'pages#intellectual-property-law'
  get "currencies", to: 'pages#currencies'
  get "philosophy" , to: 'pages#philosophy'
  get "multi-currency-cards", to: 'pages#multi-currency-cards'
  get "no-more-borders", to: 'pages#no-more-borders'
  get "social-banking" , to: 'pages#social-banking'
  get "direct-debit" , to: 'pages#direct-debit'
  get "fraud-protection" , to: 'pages#fraud-protection'
  get "transferring-an-overseas-pension", to: 'pages#transferring-an-overseas-pension'
  get "how-to-sell-your-business" , to: 'pages#how-to-sell-your-business'
  get "is-this-website-real" , to: 'pages#is-this-website-real'
  get "scam-calls", to: 'pages#scam-calls'
  get "scam-messages", to: 'pages#scam-messages'
  get "password-protection" , to: 'pages#password-protection'
  get "using-your-card-securely", to: 'pages#using-your-card-securely'
  get "self-employed-pensions", to: 'pages#self-employed-pensions'
  get "retire-in-portugual", to: 'pages#retire-in-portugual'
  get "money-and-mental-health", to: 'pages#money-and-mental-health'
  get "blogs-small-business" , to: 'pages#blogs-small-business'
  get "blogs-travel" , to: 'pages#blogs-travel'
  get 'blogs-personal-finance', to: 'pages#blogs-personal-finance'
  get 'blog', to: 'pages#blog'
  get 'where-to-visit-post-covid', to: 'pages#where-to-visit-post-covid.html'
  get 'our-fees', to: 'pages#our-fees'
  get 'so-you-want-to-save', to: 'pages#so-you-want-to-save'
  get 'travel-safety-recording-devices', to: 'pages#travel-safety-recording-devices'
  get 'get-funding-for-your-startup', to: 'pages#get-funding-for-your-startup'
  get 'startups-preparing-for-the-worst', to: 'pages#startups-preparing-for-the-worst'
  get 'do-i-really-need-a-loan', to: 'pages#do-i-really-need-a-loan'
  get 'travel-scams-to-avoid', to: 'pages#travel-scams-to-avoid'
  get 'how-to-get-a-bargain-plane-ticket' , to: 'pages#how-to-get-a-bargain-plane-ticket'
  get 'are-you-doing-these-essential-things' , to: 'pages#are-you-doing-these-essential-things'
  get 'what-is-a-negative-interest-rate', to: 'pages#what-is-a-negative-interest-rate'
  get 'should-i-study-abroad:italy', to: 'pages#should-i-study-abroad:italy'
  get 'what-to-look-when-hiring', to: 'pages#what-to-look-when-hiring'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end

	def home
	end

	def blog
	end

	def professional
	end

	def terms
	end

	def privacy
	end

	def cookies
	end

	def contact
	end


  	def careers
  	end

  	def article1
  	end

  	def article2
  	end

  	def article3
  	end

  	def article4
  	end

  	def article5
  	end

    def article6
    end

    def article7
    end

    def article8
    end

    def article9
    end

    def article10
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/pages/accounting-software-for-small-businesses.html.erb
   <div class="navigation-wrap start-header-blog start-style">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-md navbar-light">
            <%= link_to "/", class: "navbar-brand" do %>
              <%= image_tag "KP_Logo2.png" %>
            <% end %>

    <div class="navigationbarblog">

      <a rel=noopener href="/">Personal</a>
      <a rel=noopener href="/professional">Business</a>
      <div class="animation start-home"></div>
    </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto py-4 py-md-0">
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                  <a class="nav-link" rel=noopener href="#"aria-expanded="false"><%= link_to"ABOUT US", about_path%></a>&nbsp &nbsp&nbsp
                  <a rel=noopener class="nav-link" href="/blog"aria-expanded="false">BLOG</a>&nbsp &nbsp&nbsp
                  <a class="nav-link" rel=noopener href="https://support.kiyanpay.com/en/"aria-expanded="false">SUPPORT</a>
                </li>
              </ul>

              <div class="position-btn">
                <div class='brk-btn'><a rel=noopener href="https://gate.kiyanpay.com/signup">Sign Up</a></div>
              </div>
              &nbsp&nbsp <a class="greybold" href="https://gate.kiyanpay.com/login">Login</a>
            </div>

            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>



<!-- Very important to make jquery work -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>




<article>


  <h1>Best Accounting Software's for Small Businesses:</h1>

      <div class="time">
    <time><%= request.location.city %> - <%= Date.today.strftime("%a, %e %b %Y") =%> </time>

    <ul class="social-icons"><br>
      <li><a class="facebook" rel=noopener href="https://www.facebook.com/sharer/sharer.php?u=https://www.kiyanpay.com/accounting-software-for-small-businesses" target="_blank" > <i class="fa fa-facebook"></i></a></li>
      <li><a class="twitter" rel=noopener href="https://twitter.com/intent/tweet?url=https://www.kiyanpay.com/accounting-software-for-small-businesses" target="_blank"><i class="fa fa-twitter"></i></a></li>
      <li><a class="linkedin" rel=noopener href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.kiyanpay.com/accounting-software-for-small-businesses" target="_blank" ><i class="fa fa-linkedin"></i></a></li>
    </ul>
  </div>


<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/H7NcT04/Screenshot-2021-04-15-at-11-54-58.png" alt="">
</div>


  <section class="articles">


    <p lang="en">We told you we want to do all the hard work and let you focus on your business and we meant it!</p><br>

    <p>That’s why we’ve compiled our top picks for the best accounting softwares for small businesses. Why waste time? We’re diving in with our number 1 pick.</p><br>

    <h2>1. FreshBooks</h2>

    <p>We’re not alone in saying that FreshBooks is our number 1 choice for accounting software, especially for beginner accounting entrepreneurs and small business owners</p><br>

    <p>The interface is intuitive and easy to grapple with and there is a lot of help from the customer service team to aid you in your journey of accounting discovery</p><br>

    <p>Here is a breakdown of the pricing and features:</p><br>


<div class="mainpicture">
      <img id="pic" class="center" src="https://i.ibb.co/RcbwLK4/account1.jpg" alt="">
</div>

    <br><li>FreshBooks' Features:</li><br>

    <p>&nbsp•&nbsp Payment reminders</p>
    <p>&nbsp•&nbsp Time tracking with a Chrome browser extension</p>
    <p>&nbsp•&nbsp Recurring invoices with customizable options including due dates and discounts</p>
    <p>&nbsp•&nbsp Online credit card payments</p>
    <p>&nbsp•&nbsp Remembered vendors</p>
    <p>&nbsp•&nbsp Multi-currency and language billing</p>
    <p>&nbsp•&nbsp Automatic tax calculations on sales tax</p>
    <p>&nbsp•&nbsp Easily integrates with other products (GSuite and Gusto)</p>
    <p>&nbsp•&nbsp Tax-friendly expense categories</p>
    <p>&nbsp•&nbsp Bank deposits, recurring payments, and auto bills with bank integration</p>
    <p>&nbsp•&nbsp Tax help integrations with tax apps, estimates, deductions, and filing tools</p><br>

    <li>FreshBooks' Pricing:</li><br>


    <p><u>Lite:</u> $6 per month for the self-employed business owner with five billable clients</p><br>

    <p><u>Plus:</u> $10 per month for businesses with 50 billable clients</p><br>

    <p><u>Premium:</u> $20 per month for growing businesses with up to 500 billable clients</p><br>

    <p><u>Select:</u> Custom features and pricing for businesses with more than 500 billable clients</p><br>

<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/m4X2f5n/money2.png" alt="">
</div>

    <h2>2. Wave Accouting</h2>

    <p>We like Wave because it’s the best value for money. You have access to all of the basic features and it isn’t trying to break the bank! It’s great for those who are just starting out and want to try before they buy!</p><br>

    <li>Wave Features:</li><br>

    <p>&nbsp•&nbsp Unlimited income and expense tracking</p>
    <p>&nbsp•&nbsp Track sales tax on income and expenses</p>
    <p>&nbsp•&nbsp Double-entry system</p>
    <p>&nbsp•&nbsp Multiple users</p>
    <p>&nbsp•&nbsp Dashboard with easy-to-read financials</p>
    <p>&nbsp•&nbsp Organize income and expenses into tax categories</p>
    <p>&nbsp•&nbsp Reports including profit and loss statements and cashflow</p><br>

    <li>Wave Pricing:</li><br>

    <p>The accounting, receipt scanning, and invoicing software is free with no hidden charges</p><br>
    <p>Credit card processing is 2.9% plus $0.30 for Visa, Mastercard, and Discover and 3.4% plus $0.30 for American Expres</p><br>
    <p>Bank Payments (ACH): 1% per transaction with a $1 minimum fee</p><br>
    <p>Payroll: $35 monthly base fee plus $6 per active employee and $6 per independent contractor, and payroll taxes are handled by the company (only available in certain states)</p><br>

<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/RHCtm1g/account3.png" alt="">
</div>

    <h2>3. Xero Accounting</h2>

    <p>Xero has been around for a while and with good reason. It is a go to for a lot of businesses because of its user-friendly interface and extensive and ever-updating features. It is multiple user and team friendly too!</p><br>

    <li>Xero Features:</li><br>

    <p>&nbsp•&nbsp Create expense claims</p>
    <p>&nbsp•&nbsp Send invoices</p>
    <p>&nbsp•&nbsp Fast bank reconciliation and integration with your financial institution and other apps including HubSpot, Square, and over 450 different programs</p>
    <p>&nbsp•&nbsp Up-to-date financial reports</p>
    <p>&nbsp•&nbsp Business data protected</p>
    <p>&nbsp•&nbsp Real-time cash position</p>
    <p>&nbsp•&nbsp Collaborate with staff or your accountant</p><br>


    <li>Xero Pricing:</li><br>


    <p><u>Early:</u> $4.50 per month, send 20 invoices, enter five bills, reconcile bank statements, and capture bills and receipts</p><br>
    <p><u>Growing:</u> $30 per month, send invoices and quotes, enter bills, reconcile bank statements, and capture bills and receipts</p><br>
    <p><u>Established:</u> $60 per month, includes all Growing tier features plus multi-currencies, expenses, and projects</p><br>

<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/XWqyjth/quick.jpg" alt="">
</div>

    <h2>4. Intuit QuickBooks</h2>

    <p>Intuit is a cult favourite and we’re in support! It’s easy to use and beginner friendly so there is no need to worry if you haven’t got much experience. It is also geared towards small to medium businesses so there are plenty of features which cater to a smaller team.</p><br>

    <li>QuickBooks Features:</li><br>

    <p>&nbsp•&nbspFinancial institution integration as well as integration with PayPal, Square, Shopify, and more</p>
    <p>&nbsp•&nbsp Help to file quarterly and annual tax returns with user guides and exporting tax data</p>
    <p>&nbsp•&nbsp Sales tax calculations, returns, and recorded tax payments</p>
    <p>&nbsp•&nbsp Automatically sort transactions and expenses into tax categories
    </p>
    <p>&nbsp•&nbsp Track expenses in one place</p>
    <p>&nbsp•&nbsp Scan receipts and attach them to invoices</p>
    <p>&nbsp•&nbsp Share with your accountant or export documents</p>
    <p>&nbsp•&nbsp Create customized reports with cashflow tracking visible on your dashboard</p>
    <p>&nbsp•&nbsp Track miles with your smartphone’s GPS</p><br>

    <li>QuickBooks Pricing:</li><br>

    <p><u>Simple Start:</u> $12.50 per month for businesses just getting started</p><br>
    <p><u>Essentials:</u> $20 per month for managing growing businesses</p><br>
    <p><u>Plus:</u> $35 per month to help you get better organized and manage projects, inventory, and contractors</p><br>
    <p><u>Advanced:</u> $75 per month to help your business grow with deeper insights and dedicated support</p><br>

    <p>We wish you a happy accounting (does that exist?) and we hope that you find the software that works for you! All of the mentioned programs have free trials so make sure to try before you buy :)</p>



<div class="user-profile">


</div>
  </section>

</article>

app/views/pages/article3.html.erb
   <div class="navigation-wrap start-header-blog start-style">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-md navbar-light">
            <%= link_to  "/", class: "navbar-brand" do %>
              <%= image_tag "KP_Logo2.png" %>
            <% end %>

    <div class="navigationbarblog">

      <a rel=noopener href="/">Personal</a>
      <a rel=noopener href="/professional">Business</a>
      <div class="animation start-home"></div>
    </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto py-4 py-md-0">
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                  <a class="nav-link" rel=noopener href="#"aria-expanded="false"><%= link_to"ABOUT US", about_path%></a>&nbsp &nbsp&nbsp
                  <a class="nav-link" rel=noopener href="#"aria-expanded="false"><%= link_to"BLOG", blog_path%></a>&nbsp &nbsp&nbsp
                  <a class="nav-link" rel=noopener href="https://support.kiyanpay.com/en/"aria-expanded="false">SUPPORT</a>
                </li>
              </ul>

              <div class="position-btn">
                <div class='brk-btn'><a rel=noopener href="https://gate.kiyanpay.com/login">Log in</a></div>
              </div>

            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>



<!-- Very important to make jquery work -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>




<article>


  <h1>Financial Security</h1>

      <div class="time">
    <time><%= request.location.city %> - <%= Date.today.strftime("%a, %e %b %Y") =%> </time>
    <ul class="social-icons"><br>
      <li><a class="facebook" rel=noopener href="https://www.facebook.com/sharer/sharer.php?u=https://www.kiyanpay.com/article3" target="_blank" > <i class="fa fa-facebook"></i></a></li>
      <li><a class="twitter" rel=noopener href="https://twitter.com/intent/tweet?url=https://www.kiyanpay.com/article3" target="_blank"><i class="fa fa-twitter"></i></a></li>
      <li><a class="linkedin" rel=noopener href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.kiyanpay.com/article3" target="_blank" ><i class="fa fa-linkedin"></i></a></li>
    </ul>
  </div>


<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/MRMVdnN/finance1.jpg" alt="">
</div>


  <section class="articles">


    <p lang="en">Financial security is usually defined as a feeling in control of your income and spending. In other words, you're making more than you're spending and you feel good about it!</p><br>


    <h2>Why Should We Care About Financial Security?</h2>

    <p>Financial security is so much more than covering expenses. It's knowing how to budget, having healthy savings and being able to sleep through the night.</p><br>

    <p>Being financial secure removes the guilt and stress which can surround spending. Particularly during a pandemic when even national financial security was in question.</p><br>


<div class="mainpicture">
      <img id="pic" class="center" src="https://i.ibb.co/zN0VdyV/finance2.jpg" alt="">
</div>


    <h2>Where Do We Start?</h2>

    <p>It can be overwhelming to have to reprogram your spending habits. Especially if you're being underpaid and over-worked so don't have the extra time to spend. That's why we recommend budgeting.</p><br>

    <p>We know... BUDGETING. Who hasn't shoved it down your throat as a solution to money problems? The truth is, you can't budget £600 into £1200 but you can make sure it doesn't turn into £100 before you know it.</p><br>

    <p>Our advice?</p><br>

    <p>Take one day, preferably near payday, to set out your budget for the entire month. Separate your allowance into necessary, preferred and luxury.</p><br>

    <p><u>Necessary:</u> Rent, Bills and Food.</p><br>

    <p><u>Preferred:</u> Online Shopping, Eating out and Entertainment.</p><br>

    <p><u>Luxury:</u> One-off events e.g. holidays, expensive dinner dates and new shoes!</p><br>

    <p>We should probably be telling you to put aside a considerable amount to save right now. But, for a lot of people, that's a luxury too. If you're able to put the money aside, 10% of your monthly income will take
    the pressure off of you on days where you can't go into work, you're stuck between jobs or your cat needs an expensive surgery.</p><br>

<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/zFyPpBJ/finance3.jpg" alt="">
</div>

    <h2>Long Term Vs Short Terms Goals:</h2>

    <p>What are you supposed to prioritise? That depends!</p><br>

    <p>What is more important to you? Financial security is not a one size fits all strategy. You need to decide whether there are things that you want to save up for or whether you prefer to spend your extra income on small things here and there.</p><br>

    <p>Financial security should feel freeing, but it can often involve a feeling of constriction. Why? Because too many people are confusing not spending with securing their financial future.</p><br>

    <p>If you're feeling the pressure to put all of your money away when you would rather indulge periodically, that's okay too. As long as you're not spending more than you're earning or being frivolous (what does that even mean anyway?)... we support you!</p><br>

<div class="mainpicture">
    <img id="pic"  class="center" src="https://i.ibb.co/Y2y8n67/finance4.jpg" alt="">
</div>

    <h2>Emergencies:</h2>

    <p>No one wants to think that they're susceptible to financial emergencies. We're bulletproof, right?</p><br>

    <p>But prevention is the best cure. So if you prepare for something that never happens you'll fare a lot better than being hit by a tragic surprise. This is where intelligent saving comes in.</p><br>

    <p>You can save in small increments so you don't feel the money
    leave your account or you can commit to a certain amount that you want to put aside. Either way, making sure that the future you has something to lean back on will be something they'll certainly thank you for.</p><br>

<div class="mainpicture">
    <img id="pic" class="center" src="https://i.ibb.co/YpqMQdp/securt.jpg" alt="">
</div>

    <h2>Tracking Spending:</h2>

    <p>Forethought is important, but you can learn a lot more from hindsight and reflection</p><br>

    <p>When you're setting the budget for next month take some time to notice patterns in your card tapping! Are you spending a lot on eating out or online shopping? Or maybe you're being very frugal and you can
    afford to go a little crazier next month. Either way, it's useful to see what changes can put you in a better place for next month.</p><br>

    <p>We wish you happy spending (and saving)!</p><br>

    <p>KiyanPay</p><br>


<div class="user-profile">
  <img id="pic" class="avatar" src="https://i.ibb.co/ZVypMn8/Screenshot-2021-04-16-at-12-19-22.png" alt="Ash" />
    <div class="username">Vicky Veselichka
</div>
  <div class="bio">

  </div>
</div>
  </section>

</article>

app/views/shared/_footer.html.erb
 <!-- Site footer -->
<!-- <footer class="first-footer">
   <div class="container">
   </div>
</footer> -->

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-3">
            <h6></h6>
            <p class="text-justify">
            <img src="https://i.ibb.co/hYjcvZN/fraud2.png" alt="" />
            <img src="https://i.ibb.co/KjB1W49/innovatefinance-copy.png" alt="" />
            </p>
          </div>

          <div class="col-xs-6 col-md-3">
            <div class="title-footer"><h6>ABOUT US</h6></div>
            <ul class="footer-links">
              <li><%=  link_to"Who We Are", about_path%></li>
              <li><a href="/blog">Blog</a></li>
              <li><%=  link_to"Careers", careers_path%></li>

            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <div class="title-footer"><h6>Quick Links</h6></div>
            <ul class="footer-links">
              <li><a href="/fraud-protection">Fraud Protection</a></li>
              <li><%=  link_to"Privacy Policy", privacy_path%></li>
              <li><%=  link_to"Terms & Conditions", terms_path%></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <div class="title-footer"><h6>Address</h6></div>
            <ul class="footer-links">
              <li>40 Gracechurch Street</li>
              <li>EC3V 0BT</li>
              <li>London, UK</li>
            </ul><br>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-10 col-sm-6 col-xs-12"><br>
            <p class="copyright-text">Kiyanpay is registered by the Financial Conduct Authority under electronic money transfer and payment services Ref No: 814005 and is licensed and regulated by HMRC as a Money Service Business (MSB - license no. XRML00000131603). Kiyanpay is not a bank, the Kiyanpay account is an e-money account. <br><br><br>
            </p>
          </div>

          <div class="col-md-2 col-sm-6 col-xs-12">
            <ul class="social-icons"><br>
              <li><a rel=noopener class="facebook" href="https://www.facebook.com/kiyanpayltd"><i class="fa fa-facebook"></i></a></li>
              <li><a rel=noopener class="twitter" href="https://twitter.com/kiyanpay"><i class="fa fa-twitter"></i></a></li>
              <li><a rel=noopener class="instagram" href="https://www.instagram.com/kiyanpay/"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
   <div class="navigation-wrap start-header start-style">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-md navbar-light">
            <%=  link_to "/", class: "navbar-brand" do %>
              <%= image_tag "KP_Logo2.png" %>
            <% end %>

    <div class="navigationbar">
      <a rel=noopener href="/">Personal</a>
      <a rel=noopener href="/professional">Business</a>
      <div class="animation start-home"></div>
    </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto py-4 py-md-0">
                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                  <a rel=noopener class="nav-link" href="#"aria-expanded="false"><%= link_to"ABOUT US", about_path%></a>&nbsp &nbsp&nbsp
                  <a rel=noopener class="nav-link" href="/blog"aria-expanded="false">BLOG</a>&nbsp &nbsp&nbsp
                  <a rel=noopener class="nav-link" href="https://support.kiyanpay.com/en/"aria-expanded="false">SUPPORT</a>
                </li>
              </ul>

              <div class="position-btn">
                <div class='brk-btn'><a rel=noopener href="https://gate.kiyanpay.com/signup">Sign Up</a></div>
              </div>
              &nbsp&nbsp <a class="greybold" href="https://gate.kiyanpay.com/login">Login</a>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>






<!-- Very important to make jquery work -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>